---
- hosts: local
  tasks:
    - name: Add rpmfusion
      become: true
      dnf:
        state: present
        disable_gpg_check: yes
        name:
          - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts.distribution_version }}.noarch.rpm
          - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts.distribution_version }}.noarch.rpm

    - name: Install VS Code - Import key
      become: true
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Install VS Code - Add repo
      become: true
      ansible.builtin.shell:
        cmd: 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

    - name: Update package list
      become: true
      dnf:
        update_cache: true

    - name: Upgrade all packages
      become: true
      dnf:
        name: '*'
        state: latest

    - name: Install basic packages
      become: true
      dnf:
        state: latest
        name:
         - libreoffice
         - vlc
         - gimp
         - nomacs
         - discord
         - steam
         - chromium
         - firefox
         - doublecmd-qt
         - gnome-tweaks
         - neofetch
         - htop
         - rofi
         - remmina

    - name: Install dev packages
      become: true
      dnf:
        state: latest
        name:
         - vim
         - vim-powerline
         - curl
         - wget
         - git
         - mc
         - kitty
         - xterm
         - tmux
         - g++
         - golang
         - dotnet-sdk-6.0
         - java-17-openjdk
         - npm
         - code
         - ghostwriter

    - name: Setup gnome
      include_tasks: gnome-settings.yml

    - name: Dotfiles setup
      include_tasks: dotfiles.yml
