---
- hosts: local
  tasks:
       
    - name: Install VS Code - Add repo/Import key
      become: true
      yum_repository:
        name: Code
        description: VS Code YUM repo
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc

    - name: Update package list
      become: true
      dnf:
        update_cache: true

    - name: Upgrade all packages
      become: true
      dnf:
        name: '*'
        state: latest

    - name: Uninstall unnecessary packages
      become: true
      dnf:
        state: absent
        autoremove: yes
        name: 
          - loupe
          - gnome-tour
          - gnome-weather
          - gnome-contacts
          - gnome-maps
          - totem
          - evolution
          - rhythmbox
          - cheese
          - yelp

    - name: Install basic packages
      become: true
      dnf:
        state: latest
        name:
         - libreoffice
         - vlc
         - gimp
         - nomacs
         - discord
         - steam
         - chromium
         - firefox
         - doublecmd-gtk
         - gnome-tweaks
         - neofetch
         - htop
         - rofi
         - remmina

    - name: Install dev packages
      become: true
      dnf:
        state: latest
        name:
         - vim
         - vim-powerline
         - curl
         - wget
         - git
         - mc
         - kitty
         - xterm
         - tmux
         - g++
         - golang
         - dotnet-sdk-8.0
         - java-21-openjdk
         - npm
         - code
         - ghostwriter

    - name: Setup gnome
      include_tasks: gnome-settings.yml

    - name: Dotfiles setup
      include_tasks: dotfiles.yml
