---
- name: Keybindings -- Close application
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/close"
    value: "['<Super>q']"

- name: Keybindings -- Minimize application
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/minimize"
    value: "['<Super>h']"

- name: Keybindings -- Rofi open
  become: true
  ansible.builtin.shell:
    cmd: dconf load / < ~/.setup/custom_keybindings.conf
